### ISSUE TITLE
Allow public access to the PMP

### ISSUE THREAD

**Issue by cavis** [npr/pmp-issues#27]
See publicmediaplatform/pmpcode#70

> Some salient points out of the Tech Summit:
> 1. preserve spirit of "public" in PMP by avoiding the use of Permissions wherever possible;
> 2. common whitelists (https://github.com/publicmediaplatform/pmpprojectmanagement/wiki/PMP-Summit:-Managing-Shared-Groups#summary) of public media content consumers;
> 3. browsable PMP can provide access to whitelisted items since the user account the browser app uses could be added to the relevant whitelists
> 4. self-service API key registration still a goal (https://github.com/publicmediaplatform/pmpprojectmanagement/wiki/Beyond-the-Core-Build:-PMP-Tech-Summit#action-items)

**Comment by dgorsline** [comment]
Migrated to http://confluence.npr.org/display/TECH/Feature+request%3A+Allow+public+access+to+the+PMP
