### ISSUE TITLE
Creating more intuitive blacklists

### ISSUE THREAD

**Issue by CrookedNumber** [npr/pmp-issues#44]
Blacklists don’t really work as you might expect. If you have JUST a blacklist perm — which is _not_ recommended — the doc effectively becomes private. A blacklist needs a complementary whitelist (or several) to operate as expected. And the most anticipated use-case for blacklists — a station wants to expose the doc to everyone EXCEPT station X (and maybe station Y too) — isn’t even possible right now in the PMP. (Well, it’s theoretically possible, but not practically.)

Such a scenario would involve a blacklist perm (banning station X and Y) as well as a whitelist perm for all stations. But there IS no realistic way to whitelist all stations. Well, actually there is, which is no have no perms at all on the doc, but that leaves no room for the blacklist perm we want to include. So we’re stuck.

One quick, non-disruptive solution would be: PMP creates a group that is **all** users, and auto-updates it any time a user is added to the API. Though this does seem to be solving a more abstract spec problem via a cron in the API, which seems a bit ... wrong.

Any other possible solutions?

**Comment by dgorsline** [comment]
Migrated to http://confluence.npr.org/display/TECH/Feature+Request%3A+Creating+more+intuitive+blacklists
