### ISSUE TITLE
Implement a has_created param

### ISSUE THREAD

**Issue by CrookedNumber** [npr/pmp-issues#46]
Ryan and I were talking about this earlier. People will need (or have already written) clients which want to filter docs by creator. Now, we could create a dropdown of all users (or orgs), but that would give you a lot of noise. If, however, there were a param you could add to return only creators where # of created docs > 0, you would get back exactly what you wanted (all pure signal).

I'll let Ryan talk about the associated hurdles (re: caching).

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4052
