### ISSUE TITLE
Media types with parameters are not supported

### ISSUE THREAD

**Issue by mpilone** [npr/pmp-issues#5]
While starting to write a simple Java client to the PMP API using [Apache HTTP Components](https://hc.apache.org/) I ran into an issue trying to create client credentials. It appears that the media-type set on the content-type header is strictly parsed and compared to "application/x-www-form-urlencoded" which does not support optional parameters. According to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7), a media type can have any number of parameters separated by semi-colons.

For example, this request works:

```
curl --user pmpuser:pmppass -X POST "https://publish-pilot.pmp.io/auth/credentials" -d "scope=read" -d "token_expires_in=360" -d "label=foo" -L -m 5 -v
```

while this request fails with a "415 Unsupported Media Type":

```
curl --user pmpuser:pmppass -X POST "https://publish-pilot.pmp.io/auth/credentials" -d "scope=read" -d "token_expires_in=360" -d "label=foo" -L -m 5 -v -H"Content-Type: application/x-www-form-urlencoded; charset=UTF-8"
```

The difference being the "; charset=UTF-8" parameter on the content-type.

The bug is in the parseUrlEncoded.js file around line 5 where the entire header is checked for equality. The same bug probably exists in the other content-type checking middleware.

Proper support for different character sets should also be verified when parsing documents to make sure UTF-8 is actually supported properly or there will be odd character transformations later.

**Comment by dgorsline** [comment]
Migrated to http://confluence.npr.org/display/TECH/Feature+request%3A+Media+types+with+parameters+are+not+supported
