### ISSUE TITLE
Contributed data

### ISSUE THREAD

**Issue by cavis** [npr/pmp-issues#62]
See [this forum thread](https://discuss.pmp.io/t/contributed-unofficial-pmp-data/144/25).  Attempting to capture the TODO list for implementation.
1. Create an "Annotation Profile" document/alias
   - Extend `profiles/pmpcore`.
   - Create at least a couple sub-profiles (geotag, transcript, etc) as examples of common annotations.  They'll probably need schemas defined.
2. Define a `links.describes` relation type on the `annotation` schema
   - Based on [RFC6892](http://tools.ietf.org/html/rfc6892#ref-2)
   - Will be set on annotations, to point to docs they describe
3. Define a `?describes=GUID` query param
   - For finding annotations on a known document
   - Returns any documents describing that GUID
   - Querying `?describes=GUID&profile=annotation` would theoretically be the same - unless a non-annotation doc used the `link.describes`
4. Define another `Prefer: return=describes` header
   - For transcluding annotations in a single JSON response
   - Will set a top-level `describes` key, to the results of `?describes=GUID`
     - Hmmm... paging the `describes`???  Probably skip it, for now.
5. Define a `?annotations=1` query param (defaults to 0)
   - When set, your search will also return documents described-by matching annotations
   - The following query params will only match on the primary document:
     - `guid, limit, offset, searchsort, writeable` - these only make sense on the primary doc
     - `profile, creator, owner, distributor, distributorgroup` - an annotation should never change these
   - The following query params will also match on the describing annotations:
     - `tag, itag, language, collection, item, author, location, distance, text`
   - Not sure what to do with these yet
     - `startdate, enddate` - could an annotation ever change the published date?
     - `has` - this is tricky ... if I want to use an annotation to add a `links.item`, do I need to include any other `links.item` on the original doc?  Is this true for other link types?  Collection, author, etc?

**Comment by cavis** [comment]
Phew!  This is complicated!

**Comment by dgorsline** [comment]
Migrated to http://confluence.npr.org/display/TECH/Feature+request%3A+Contributed+data
